##服務提供者
server:
  port: 8086

spring:
  application:
    name: provider
dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    id: provider
    name: provider
  scan:
    basePackages: com.chad.provider.service  #提供者 @Serivce 所在 package
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://127.0.0.1:2181
    id: my-registry
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: 20880
    id: dubbo
